selected_preset = ""

[output_colors]
Error = "red"
Warning = "light_green"
SystemOut = "yellow"
Advice = "magenta"
Other = "white"
cPrompt = "dark_grey"

[file_colors]
Direc = "blue"
Text = "magenta"
Program = "green"
Other = "yellow"
